apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubesphere-ingress
  namespace: kubesphere-system
spec:
  ingressClassName: nginx
  rules:
  - host: "ks.loc"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ks-console
            port:
              number: 80
